language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install git+https://github.com/UBC-MDS/tidyplusPy.git
  - pip install -r requirements.txt
  - pip install -U pytest
# command to run tests
script:
  - pytest
  - py.test --cov=./tests/


after_success:
  - codecov
